version: "3.9"

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/app/config.yml  # Mount configuration file
      - ./screenshots:/app/screenshots  # Mount screenshot directory
    restart: always
    network_mode: "host"  # Use host networking
